language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master

notifications:
  email:
  - komuisan@gmail.com

install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd tests
    - coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: efrem
    password:
      secure: "PdklGL2cimRlQDdHwCkAtXZ1GjaWJ1G82SXvt7N21xJUcy22cUNKEFlUXCF4ysj2YpI8n+MUhSAuhlCii07s5qpXP/CLVrYPfZ4GISlzgfhjFz0zFWJDlnvfXBs3ya8UMXvP/UuzQeQc6WJEBrvrMNsMPzoPr7iyzfOJp+T8758y3j4Z807wb6UPMT8uptKnZms0cHRrOhlgcxm8/2K0WSTEaA5GbPVCONzE3GollvmhO4RbwVOe3Xr1kfsMp0ENd46jqrhH7CCGxSkkBCFlv074JvzP5pQn8RxDqIjnG3y4VdFcd+YKWH1hocDdRls4hcGPv7df1Pk9eEQ+K2C2gXQWoc/f53OV9j4HEMQo3m0Gkqalg75Iu/E/qQDkk89r8hGkjZiyOOxthpMQwg33/viztxEAFw1Q2kKzJTDIP358qVI7T/c8vm7wLcDHz7UHAxBKLbP4tve0Lk6HsrYuRJz8paNh4G/uurs7Dfh+5AYTVuMXi23mQ3n8zBPFSiz16qc/Y4C0sA/wzG5U2dX5KkAPZrxeShLFL8G/cL81l1RjY4rhwDVMSHWMyHEXJ0Pf0MHoI7p2GeqGsrISE8/UifcLjvaM3Qe0SBUljEwweOES/R33gd1jOnM8vi7AoBhRcPLu3YHaFNsFNKpwnsTAz0muiXbUYxo/WRY9bso2rjY="
    skip_existing: true
    on:
      branch: master
      tags: false