language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
  - provider: pypi
#    distributions: sdist
    user: "__token__"
    password:
      secure: "pypi-AgEIcHlwaS5vcmcCJDY3NmM4YjdkLWNiYzEtNDNmNC1iY2ZjLTY5ZmJkNTU3ZmQzYQACOXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJodWNrZWxweSJdfSwgInZlcnNpb24iOiAxfQAABiDjty7gaDeUKyEX5j81tgE_H_dszdakS4m3fgy604zDZA"
#    skip_existing: true
#    on:
#      branch: master
#      tags: false
