language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
- provider: pypi
  distributions: sdist
  user: efrem
  password:
    secure: 0/YYVswZXAIfjQkvUr+B/7oXxfGcq8QxM5Z2RxHlxuPLc4k+xpuu7jcXiWRzJBHQK6gqoorr5t8VPAcNCsKvc7pya7J4q0uc6M7PO6E4Q6PBybO2LMPnwxULONK2sJEZ6h4CAAcVSRKwx71OcGhkpv8el4WZgTOLZ/aWCLBpk1uelHINQxb3zqEJtvvNG4Ex7R741I8wV8vx8EsUczyknWJIlOg0ybPjlPo7czUWlM6FW/FKEBloAu3lffL0nHUGMelTH1HhewQtZYrwVX331ZC+9b30FiMBPEEU77ZEtqTfV0f3HiM7jeyurinuCzFXcgNCgQ0n1A+OhgicbGdM5iCZxOHJJAGjfduWmVpIWJRgUXdPCmi4L6hpNoYki/BeAU21zQChqAEWc1XmPGC0wQ6VVXnm3GzJsC5wzDTm4OoPlLHpQUhQwBgK/Cj48JW/vOuKEKE3YeIxWV5/WAkz+XvaXo+LG9FZWBQZYBkCmqxk5O5RKpdAP+WYoeKRNJLvNAesPhjXZ2cin88jrHIGZLZYrgXHo1h3+U5M7okJ3FsWsm76SsQnMzWDoDeCSCLEGHT5Wfx2hc70woQ4mULlFtRQZLuF7HpcaJ+1utoo70b7EYHHmyiId7QHD6LAmBykAdmB8f7Zz9XVVaIEmkccJ6juSuJKyUn0guWppa99Bco=
#  skip_existing: true
#  on:
#    branch: master
#    tags: false
