language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
  - provider: pypi
    distributions: sdist
    user: efrembernuz
    password:
      secure: "11gyLxZhMr4Z5GLs5F9Kxr5ru/5d5KWDJEJCLeBNOGOStnGCwN7fnY11U5tYWv+Po7Pk/mYYu87LJbYcckhaIdmCyMTfmHEYwgzTvo76y0dAZVPiqnQ3z28MS5aIsiWf5gJ7w5pEoo1Coir7IzzGPXz1jx6vIu5bHmcA9N1VXdb5r7osVUWfCCnIkzZL7JookHwHM+tXyy0QpT/d6mHuNAj5Fk4072DFvg006YZoyVtsjaSARKBkA6bx4pyo8jHI7s0aU/wQ+cSjb5QgtZAewQXYJmOzP/4CXicA+J/gN0ib03Py21fnsRnfUhkprxZkNYV3M11T2fgoyEt2vv2hTZKBI7eDfzMknTUdPLnHD/tDzOgeFHVCKCcj6O++MtEOlffgGRy1Br5Orgunc0HoMZmVub+4j4w06JueYPtChfPJADsQglwnewo/haQqCo2nAjXp5tfCzrY3I15ShK09MDZSvmYtyRCOcjj3JVH0Cy2rbQNoIUtrVFX/cJLo0m+H7aZM8OVzEnhBBJMcRBjr/RRYNk6nFmycO2URRZHFvSU4HHxfD9tXwGLJgdn2/PDOA5jsJzkV/gWsBi1H2b3SMGa70/+HhzikZChfYbkQJudpCuGlLzmZbpQ7M/ho15aPvDZayz71WiEyoXbh27GoZ0uyxHKMx8yuFoeAPxwBtwY="
    skip_existing: true
    on:
      branch: master
      tags: false
