language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
  - provider: pypi
#    distributions: sdist
    user: "__token__"
    password:
      secure: "pZPYlFCocYc71P9Y+APAeO8/+5NuNKK2T/BMSvFNIRpGDOIkoqM0JS4HiB4MshfrdNJ6RmGDAEfWDj+BSGxyNufjWKMDqmvDkKYu0vhfpHrJh3WK7MkGd+zj/0umvUWmCGVOb1jUwt3S82mYo2qf0KvWQEVBe+cYHGmlpwh/FhE7+qMZzzJsHYrs+tx8c3u+FSfNGd0t8Twshm/o5dIuA34Jc8rck2A6HouZNkN9VKnDJS6MfRXptpvPJqdCRwOf9G/3djoLFyV/6bJzDpmY69YMPBrkZ3vsds0Z7WHMHaaZyeDXbFzgP75VyI85f9fNmSue9xDJWT16VoHRREwJF9hXXW0c4QBpajYlXALZ5AZc0TtaqywaCPD/w+B2KZl3Athcu8XGDBZ6PHieutEJ2oNvbAvwjot85xljiTORlB5aPvgft8RUnpFjNS5E+OZP91+kvYgQjn9vL4z6DAg2L995d+y4FSBVaf3nrzlj0vcBWr/59ITYtoeTlg48SEqpjHhJI8VDfTuJ6v+seLnGi0Ktc1fDLxLzIV5vKKHGFgv2vsNn0DGTgANCeoLNQmuQ3k1p0Cf/kUQADJegvvuZ8SOtGNZgbRTf24oUp9QmRHDtTlnqQ4yafg3oGc7FYMSU9ieX68acoa7l4MvWUxW5Tp4PyKj2DBIW5ZS4Qzwgm1I="
#    skip_existing: true
#    on:
#      branch: master
#      tags: false
