language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
  - provider: pypi
    distributions: sdist
    user: efrembernuz
    password:
      secure: "ob7IJihMg/m1LHOz23VUo1wyUwbTtq5s+C0qzOS3RswBiiOhfhuKB1rcscw2IarewkI6CM+nA6Zyt3+D3n+xXqaYWCiXLqPpXUOG1FRJwOVlO1K+8hLxpJI1xZ9kcxE2F1wRElN3YzawFRRojZ8WealPF+hkPwvCL4dbGfDXlcmqsQrZeq6Sic0lnVebNeboRhh1rQ4sKgBEWVL5AJlik3hVwz1P4iX7RYktrsFgY50NV4px6G3MpgYWn4/H/9riUHp1KUJAw7sP3mYe8FjFw5XIou17h/Wiy2tFhGYVZwyDETU/Gx64rPzkUFl1dftV6VM2GzGmVPKspf9IJi2jkqwQEOav/1+m5ftHUOX1mqWwJ6DBwMBV030LngG/MLOBnCw11P3K7nc5BbatLiFHqEU1qH3zUJOwhODv012VpKRsEVQC08IFJIU+cWBeK1kUvnYYWAJaUJnXGw2pc1opHeMNyvPBZjrS30tNDykOWK86ZgENO4cETtl4W0VRsLv5W+NIFCecSzIj9/mqVtP1TB3PVU+lowZZ3IERU8yVi3I5CaOa9bCzbIegUjKPIcVpMAmKM63nM5Pr2mSTPDeGmcWNcjCF4zKE/VcZ+a44y0mO4PedxNIfLvaNDcXc0T7agKeRXqZ3j9Khm7B9DO+tYJkYrjm+5fn2mGZjKCydGAQ="
    skip_existing: true
    on:
      branch: master
      tags: false
