language: python

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master

notifications:
  email:
  - komuisan@gmail.com

install:
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd tests
    - coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: efrem
    password:
      secure: "0xaKf8H5lizs5P7gNtg1uWigHklW/kJgoDMfLNQHUV2L1TyWdbsWEkRv0Z51v5hrO1u2gNoSSuWQhLnnW6A11osn3Zc4kCa5oUv717vNRS5yWYRqfFApf1Lc55zmZac+0vmqgP9yHh8ibewz+0UizMsTB10sI+mB7/rz6xRhH28WIJUcyi9GcoSsr3xJUAaTy4jXnZoYnxZiL0+O4TKgbo0syNg7565E7f+a7Md1hVRcF0Nz/V/UEqoAye3+muoJnEawbq6bX/i0DIeP/kyX4wLc0vfQYAyNj+zlWZcP9nKLwCoieEaE2nHt8oU9bN14pbEZxQOpvD6nGN2m6VPv1waBxm6O8RhN9d5thOfD/d4ShAsj23bh0rsa91ecP6Zr56Fj66/ZE7f+phCiVrj3kNT3lVp+AkIOJY1RL7IF9Axyyxbpa6GarXs0v6emFo4FYbT3L/YE6v2YTP5sio/pi6tGGp1mMfsbn5oXqLv0+56pqDrj9fNYHEJ7KNgXLs2IccoBCC3ZUF60rxyhfGzZ6SraNgIVoHLJflMNdhszRB0miqdezgrsvkqVadzpmSF/o/2Gw0vKvo6T6G4pESaxZPSm+g7VBe0xrWMLOBUGXvBHRfSvqHEd9MbccnR87f8Sfslu2YXUeSan7An5YmhgXrcJSrV+uWCqX2gp68dDNwc="
    skip_existing: true
    on:
      branch: master
      tags: false