language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master

notifications:
  email:
  - komuisan@gmail.com

install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd tests
    - coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: efrem
    password:
      secure: "XtX27wI8mxHuV2CMuSkGkHfCSODtJRaXRwRPZhQK6o8A7OwkOoDgk9HdzcSneh0kl+mtSUiQEg2wEJ+GFcppEI7fkkHqMxG6C51SUQDo+/+dWLO2xqyUaZfQA3dEJOlRJohNLncLvMd53bgpURyiG5B7dEixGoudhQejwR4/6YfFELua1jGj41n8BWcpcPg9s47NVtL51NufDKF5+RbObxC4/yrY9jGs+n1jSWF51Ay01ZBPdAt+6f1qkFhP51pFztsp7Sr/7Nxy4nzxowwDjzeI4LlmF2kIlNJRngbp7iGF3KfsoxWXVGQKQM4TWsiw8F/coOfq+Cj6YTJkkr1ut2+kfe+kvVSdvtdwq2twif+lFO/Oj+gpgHoqikdofESdY8Q01T1QNqsBpyl/cBMssEMLTv+DQRyt2A6ZOe3fxkGTA6IrITt6YM3+dC/nP1eOMtNZ1m3AO8bfXVXfDzPqLofnH7d8EkGCtcR8sSmn/TJt0Zp3FvLydVIzAqKuv35a7qYrKnRrL/7npwzDBaPruAzagPYnDxm/gNDjmvkv14pf//S3yM3VD0dIuAHc7C6x+YFmzieNUd6y3NxwSkDcQnfCXvv7pMwrOJC6cydAoQvm5JwOiEz9ahSDe5htBdrKLE6YI6SfdjkSmUcyRvo+B4cFVObDC0sPrAWgdK0Px5E="
    skip_existing: true
    on:
      branch: master
      tags: false