language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
- provider: pypi
  distributions: sdist
  user: efrem
  password:
    secure: 0/YYVswZXAIfjQkvUr+B/7oXxfGcq8QxM5Z2RxHlxuPLc4k+xpuu7jcXiWRzJBHQK6gqoorr5t8VPAcNCsKvc7pya7J4q0uc6M7PO6E4Q6PBybO2LMPnwxULONK2sJEZ6h4CAAcVSRKwx71OcGhkpv8el4WZgTOLZ/aWCLBpk1uelHINQxb3zqEJtvvNG4Ex7R741I8wV8vx8EsUczyknWJIlOg0ybPjlPo7czUWlM6FW/FKEBloAu3lffL0nHUGMelTH1HhewQtZYrwVX331ZC+9b30FiMBPEEU77ZEtqTfV0f3HiM7jeyurinuCzFXcgNCgQ0n1A+OhgicbGdM5iCZxOHJJAGjfduWmVpIWJRgUXdPCmi4L6hpNoYki/BeAU21zQChqAEWc1XmPGC0wQ6VVXnm3GzJsC5wzDTm4OoPlLHpQUhQwBgK/Cj48JW/vOuKEKE3YeIxWV5/WAkz+XvaXo+LG9FZWBQZYBkCmqxk5O5RKpdAP+WYoeKRNJLvNAesPhjXZ2cin88jrHIGZLZYrgXHo1h3+U5M7okJ3FsWsm76SsQnMzWDoDeCSCLEGHT5Wfx2hc70woQ4mULlFtRQZLuF7HpcaJ+1utoo70b7EYHHmyiId7QHD6LAmBykAdmB8f7Zz9XVVaIEmkccJ6juSuJKyUn0guWppa99Bco=
env:
  global:
    secure: KbQsI6wt2LNf+K+oDfhINjtI1V/vcv0HYs0gWmLjTsl86UUxPQnk2IX9ewTea3S0pGvHwpu/Dx7+nQit3ULQE6J7LLKCLdcMoZn8A/c8PqdLq/O64eRNF1w6wEZiu59WmR7bMUxr2Tz9yrThovx327m0XbBUinLrhBdvaUIUs1f9cKsfK6EHiaQdiUCwkflFAGdSgUuRbIrDXOUWE/qd1zM+IzHKHriY7fH259JPWkE51wvA+TTQQRlMBYMKZ+kxs/Bge7zCJ+fhFCagrBJYp/eDysRKNg90VXuuTO5Ap2Q49n1d+MuD9foA5hBfcp3/Sb765OG+SrWzzjj4x4lHQVSxeE/jdgh4VXR0BgHtZ71x1SsuSOVrKN3oBisxOJ8h6AfJidxbvUZh76T+M48CFdZIsxw50osQg6QofV59MWe3peaa3ri3x/0MlY9q0jLEDWmA42MWBswG2DTop1WJfPX8XPGB4lRJSQzU6WRWrSc8rVl/PiHn1UK51FBLqmkKiMb4/cyKREYja2k+YBcVb7+HCGCBzlX21TSwwLSP8yhV04GOg+LSf+7L5HXuSg5hlh01TO2uHppR0aBAPos+lq9Onvr8NZH5bJ6079PGD/KLHG7I4WyeWUmMkPtuOkWXzAxgWWdp9SXFMEarHFgvghUM/G0RiZm7N+Id2/w8JPY=
