language: python
os:
- linux
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
notifications:
  email:
  - komuisan@gmail.com
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
- pip install -e .
script:
- cd tests
- coverage run --source=../ExtendedHuckel -m unittest discover . "test_*.py"
after_success:
- coveralls
- cd ..
deploy:
- provider: pypi
  distributions: sdist
  user: efrem
  password:
    secure: GMquEOnDDCv8rLCkqw2wN1dlabcwCg83vLMoUbNmMdI5DXf5udbtnJ+AUQCbNMS4ZPoPpM6Ni4ll+VosD4zD1OU0o0BoRYP7NPFz9dynleTQppjbvkO2zpSq7r/t4lx67z6TVtTqiWQjAPtqt4ST8RcZNVnUZXPRnjZDNz2DeBRhfygJ9q4s0PGp79b5jV4gaUyVKNDz+gkxu208jsbTFfgvkaQ1AKL2ljy5H4f3J7/CajhwYW2/UWDn2OtwZfMb3DmKRMGd5GNiJ6GCgpbEsPuzxdYGqy/t4asLk8aiBJvMZT65CbhhwD2VmLbM076c4ljpb9eJnwt9N52dSpjevgWbYf2wvd1NAgVQ5dWYOem36Yc6OxIHNHnwaVnofdeIJSQNLHTDXEkSCubVA7l1i96UYznsZUzNvbJQDXrjcmQPLg7Nl3yzb2SYvDkpU2BqRwtDBxOhI4pWnd8NA1JwcX3gwNnGrFfybTGsZy6W9naJ9+CtxD+Lm7GhSFj8NB4H57B8KheE3ChG7OCSOmydxf7umsYW7+T1cN7U9ZhU4yIKc2UUaHxxGl1OpQOIrJKtXyH2mbdNlxDY4sJOTxVsaJI+fUiVfHzxSxBK9fMKwubp/d+1Q6SeqBiBDK/s98PxjLHxFBH1p4BAjMLR4/oPEDxpX6GxSSJPwjRDeAsGB9s=
  skip_existing: true
  on:
    branch: master
    tags: false
env:
  global:
    secure: tyPl0zkc4cV+TK2s2y1gptKwGEroWt1vDZiFK+/0G/ShvXJLz8MQo3Fka08iw1anHcGQW4JwdC2bN2dczL5PjCyVk+rde7Vw+OV9aKfU+OkEb8Rf0KAsj8vcsSde0ZPnx25AI5zIiZz/z49rqWZ9+XYSDgM+hUwGO9sNeEclsnu8HgKKWlwxxAGyzHMl4jR00FT2aSbfa8g2yX3+FdQXSkZFYcQJQAkRNHwuzalV3KAyhzMlGtgQRq5PBsVKdwMxOhuhEu2r42GJajdmqxeIhqHFDu+8BGut9cKvYUbCnhmElCbaoZCY8T7Pzz0oMtow6s9HIqSTmS1gIIz2aRmGZwjeNZtne6vn+4tuAyjAIWNEfcMY0TXOyR+qn2BLUV/hWKwdw8UIMWSOQtT9G56LTI2ablMAZu3e4nMJi72eMJV8ZUd+PzKwMFCay9OHndVJrZbFtffTTa/nustJSNDG9RI5Hn6qs8lTN0XA9fQ0ugRU2OXgfdKdifrX+T/c8jUIYZx7rerw5YNCp9hJeRW0obi5E8Ldp4IooEJawWNw+9kLqjDfUdmm/aF3e8t7zJU0yy/DbYqZO2iuDEWI3b+YhmeyG+utU/x66HEg/AUZtuUfjVHY6zbRUoeQN3vL0XwOjA4TuScwW5RszLOUVtwGvoFiCD3s2ODAX0xFLzaLbnM=
